version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: on-failure
    environment:
      - MYSQL_DATABASE=vollmed-api
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=root-db
      - MYSQL_PASSWORD=123
    ports:
      - "3340:3306"
    expose:
      - 3340
  api_vollmedic:
    container_name: api_vollmedic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       - mysql
    restart: on-failure



